apiVersion: v1
kind: Pod
metadata:
  name: gpu-perf
spec:
  containers:
  - name: gpu-perf
    image: gcr.io/pradvenkat-gke-dev/gpu-perf@sha256:127b2bccc8176b20adcf8b75701ea59a3937f99739fc985b972a0c7ee3abf321
    command:
    - /bin/sh
    - -c
    - while true; do ./UnifiedMemoryPerf; nvidia-smi; done
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
