apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"app":"cadvisor"},"name":"cadvisor","namespace":"cadvisor"},"spec":{"selector":{"matchLabels":{"app":"cadvisor","name":"cadvisor"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"app":"cadvisor","name":"cadvisor"}},"spec":{"automountServiceAccountToken":false,"containers":[{"args":["--housekeeping_interval=10s","--max_housekeeping_interval=15s","--event_storage_event_limit=default=0","--event_storage_age_limit=default=0","--disable_metrics=percpu,hugetlb,sched,tcp,udp,advtcp","--docker_only","--store_container_labels=false","--whitelisted_container_labels=io.kubernetes.container.name, io.kubernetes.pod.name,io.kubernetes.pod.namespace"],"env":[{"name":"LD_LIBRARY_PATH","value":"/bin/nvidia/lib64/"}],"image":"k8s.gcr.io/cadvisor:v0.30.2","name":"cadvisor","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"300m","memory":"2000Mi"},"requests":{"cpu":"150m","memory":"200Mi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/rootfs","name":"rootfs","readOnly":true},{"mountPath":"/var/run","name":"var-run","readOnly":true},{"mountPath":"/sys","name":"sys","readOnly":true},{"mountPath":"/var/lib/docker","name":"docker","readOnly":true},{"mountPath":"/dev/disk","name":"disk","readOnly":true},{"mountPath":"/dev","name":"dev"},{"mountPath":"/bin/nvidia/lib64/","name":"libnvidia"}]},{"command":["/monitor","--stackdriver-prefix=custom.googleapis.com","--source=cadvisor:http://localhost:8080","--pod-id=$(POD_NAME)","--namespace-id=$(POD_NAMESPACE)"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"gcr.io/google-containers/prometheus-to-sd:v0.2.6","name":"prometheus-to-sd","ports":[{"containerPort":6061,"name":"profiler"}],"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"runAsNonRoot":true}}],"priorityClassName":"system-node-critical","serviceAccountName":"cadvisor","terminationGracePeriodSeconds":30,"tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/"},"name":"rootfs"},{"hostPath":{"path":"/var/run"},"name":"var-run"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/var/lib/docker"},"name":"docker"},{"hostPath":{"path":"/dev/disk"},"name":"disk"},{"hostPath":{"path":"/dev"},"name":"dev"},{"hostPath":{"path":"/home/kubernetes/bin/nvidia/lib64/"},"name":"libnvidia"}]}}}}
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  creationTimestamp: "2020-09-04T02:48:50Z"
  generation: 7
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
  resourceVersion: "2565549"
  selfLink: /apis/apps/v1/namespaces/cadvisor/daemonsets/cadvisor
  uid: 54b9069a-ef1e-4243-b652-4bf6249e2cd9
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
      automountServiceAccountToken: false
      containers:
      - args:
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --disable_metrics=percpu,sched,tcp,udp
        - --docker_only
        env:
        - name: LD_LIBRARY_PATH
          value: /bin/nvidia/lib64/
        image: k8s.gcr.io/cadvisor:v0.30.2
        imagePullPolicy: IfNotPresent
        name: cadvisor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 150m
            memory: 200Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
        - mountPath: /dev
          name: dev
        - mountPath: /bin/nvidia/lib64/
          name: libnvidia
      - command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=cadvisor:http://localhost:8080
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        imagePullPolicy: IfNotPresent
        name: prometheus-to-sd
        ports:
        - containerPort: 6061
          name: profiler
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cadvisor
      serviceAccountName: cadvisor
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /
          type: ""
        name: rootfs
      - hostPath:
          path: /var/run
          type: ""
        name: var-run
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/lib/docker
          type: ""
        name: docker
      - hostPath:
          path: /dev/disk
          type: ""
        name: disk
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /home/kubernetes/bin/nvidia/lib64/
          type: ""
        name: libnvidia
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 7
  updatedNumberScheduled: 2
