apiVersion: v1
kind: Pod
metadata:
  name: mat-mult
spec:
  containers:
  - name: mat-mult
    image: us.gcr.io/gracegao-gke-dev/matrix@sha256:75580c205bafeff5fa4e1d17d2e47ae5e35a8312b7ef397b0bb01d5aaa7c006d
    command:
    - /bin/sh
    - -c
    - nvidia-smi && while true; do ./matrixMul -wA=5000 -hA=5000 -wB=5000 -hB=5000; sleep 5; done
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /tmp/nvidia-mps
        name: mps
        env:
        - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
          value: "50"
#        - name: CUDA_MPS_PINNED_DEVICE_MEM_LIMIT
#          value: "50MB"
  volumes:
    - hostPath:
        path: /tmp/nvidia-mps
        type: Directory
      name: mps
  restartPolicy: OnFailure
  hostIPC: true