apiVersion: batch/v1
kind: Job
metadata:
  name: mat-mult
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: mat-mult
        image: us.gcr.io/gracegao-gke-dev/matrix@sha256:75580c205bafeff5fa4e1d17d2e47ae5e35a8312b7ef397b0bb01d5aaa7c006d
        command:
        - /bin/sh
        - -c
        - nvidia-smi; echo "[`date`] Starting"; ./matrixMul -wA=5000 -hA=5000 -wB=5000 -hB=5000; echo "[`date`] Done";
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /tmp/nvidia-mps
            name: mps
        env:
#        - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
#          value: "10"
        - name: CUDA_MPS_PINNED_DEVICE_MEM_LIMIT
          value: "50MB"
      restartPolicy: Never
      hostIPC: true
      volumes:
        - hostPath:
            path: /tmp/nvidia-mps
            type: Directory
          name: mps
  backoffLimit: 4