apiVersion: v1
kind: Pod
metadata:
  name: nbody
spec:
  containers:
  - name: nbody
    image: us.gcr.io/gracegao-gke-dev/nbody@sha256:6e346bb9cf50a3fd3df399f8afa07fdde58e05b564683d3bc3f0d13d98851249
    command:
    - /bin/sh
    - -c
    - nvidia-smi && while true; do /usr/local/cuda/samples/5_Simulations/nbody/nbody -benchmark -numbodies=10000; sleep 10; done
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
  hostIPC: true  #  needed only when using MPS, remove otherwise.
