apiVersion: batch/v1
kind: Job
metadata:
  name: nbody
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: nbody
        image: us.gcr.io/gracegao-gke-dev/nbody@sha256:6e346bb9cf50a3fd3df399f8afa07fdde58e05b564683d3bc3f0d13d98851249
        command:
        - /bin/sh
        - -c
        - nvidia-smi; /usr/local/cuda/samples/5_Simulations/nbody/nbody -benchmark -numbodies=1000000;
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4