apiVersion: v1
kind: Pod
metadata:
  name: nccl-test
spec:
  containers:
  - name: nccl-test
    image: gcr.io/pradvenkat-gke-dev/nccl-test@sha256:6289ac5c055095a5de564d578a332158a80961151465b5d11d246a735a9df096
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
